AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: SAM config for Tweeter server

#
# Global Lambda function properties. These apply to every Lambda function.
#
Globals:
  Function:
    Runtime: nodejs22.x # I Changed from 20.x
    CodeUri: ./dist/
    Layers:
      - Ref: tweeterLayer
    Timeout: 30
    MemorySize: 128

#
# Reusable blocks of configuration. These are referenced throughout the template to avoid duplication.
# &identifier is used to define a reusable block, and *identifier is used to reference it.
#
Metadata:
  x-common-policies: &commonPolicies
    - AWSLambdaBasicExecutionRole
    - AmazonSESFullAccess
    - CloudWatchFullAccess
    - AmazonDynamoDBFullAccess
    - AmazonS3FullAccess
    - AmazonSQSFullAccess

  x-common-cors-headers: &commonCorsHeaders
    method.response.header.Access-Control-Allow-Origin: "'*'"

  x-common-swagger-response-headers: &commonSwaggerResponseHeaders
    Access-Control-Allow-Origin:
      type: string

#
# AWS resource definitions
#
Resources:
  #
  # Web API
  #

  tweeterApi:
    Type: AWS::Serverless::Api
    Properties:
      Name: tweeterApi
      StageName: prd
      Cors:
        AllowMethods: "'GET,POST,PUT,DELETE'"
        AllowHeaders: "'*'"
        AllowOrigin: "'*'"
      DefinitionBody:
        swagger: "2.0"
        info:
          title: "Tweeter API"
          description: "The API for interacting with the Lambda functions that run the Tweeter project backend"
          version: "1.0"
        x-common-consumes: &commonConsumes
          - application/json
        x-common-produces: &commonProduces
          - application/json
        x-common-request-templates: &commonRequestTemplates
          application/json: $input.json('$')
        x-common-amazon-responses: &commonAmazonResponses
          default:
            statusCode: 200
            responseParameters: *commonCorsHeaders
          ".*bad-request.*":
            statusCode: 400
            responseParameters: *commonCorsHeaders
            responseTemplates:
              application/json: '{ "error": "$input.path(''$.errorMessage'')" }'
          ".*unauthorized.*":
            statusCode: 401
            responseParameters: *commonCorsHeaders
            responseTemplates:
              application/json: '{ "error": "$input.path(''$.errorMessage'')" }'
          ".*internal-server-error.*":
            statusCode: 500
            responseParameters: *commonCorsHeaders
            responseTemplates:
              application/json: '{ "error": "$input.path(''$.errorMessage'')" }'
        x-common-swagger-responses: &commonSwaggerResponses
          "200":
            description: "OK"
            headers: *commonSwaggerResponseHeaders
          "400":
            description: "Bad Request"
            headers: *commonSwaggerResponseHeaders
          "401":
            description: "Unauthorized"
            headers: *commonSwaggerResponseHeaders
          "500":
            description: "Internal Server Error"
            headers: *commonSwaggerResponseHeaders
        paths:
          #
          # Endpoint definitions
          #

          /followee/list: ##### TODO:DONE Change "/user/get" to the actual endpoint URL
            post:
              summary: "Get a paged list of followees for a user"
              description: "Returns a paged list of all users that the given user follows"
              consumes: *commonConsumes
              produces: *commonProduces
              x-amazon-apigateway-integration:
                type: aws
                httpMethod: POST
                uri:
                  ##### TODO:DONE Change "userGetFunction" to the actual function name. (Don't delete the $, {}, or .Arn suffix.)
                  ##### The function name must agree with the "Web API Lambda functions" section below.
                  Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${tweeterGetFollowees.Arn}/invocations
                requestTemplates: *commonRequestTemplates
                responses: *commonAmazonResponses
              responses: *commonSwaggerResponses

          /follower/list: ##### TODO:DONE Set endpoint URL
            post:
              summary: "Get a paged list of followers for a user"
              description: "Returns a paged list of all users that follow the given user"
              consumes: *commonConsumes
              produces: *commonProduces
              x-amazon-apigateway-integration:
                type: aws
                httpMethod: POST
                uri:
                  ##### TODO: Set function name
                  Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${tweeterGetFollowers.Arn}/invocations
                requestTemplates: *commonRequestTemplates
                responses: *commonAmazonResponses
              responses: *commonSwaggerResponses

          /feed/list: ##### TODO:DONE Set endpoint URL
            post:
              summary: "Get a paged list of a user's feed"
              description: "Returns a paged list of a specific user's feed"
              consumes: *commonConsumes
              produces: *commonProduces
              x-amazon-apigateway-integration:
                type: aws
                httpMethod: POST
                uri:
                  ##### TODO: Set function name
                  Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${tweeterGetFeed.Arn}/invocations
                requestTemplates: *commonRequestTemplates
                responses: *commonAmazonResponses
              responses: *commonSwaggerResponses

          /story/list: ##### TODO:DONE Set endpoint URL
            post:
              summary: "Get a paged list of a user's story"
              description: "Returns a paged list of a specific user's story"
              consumes: *commonConsumes
              produces: *commonProduces
              x-amazon-apigateway-integration:
                type: aws
                httpMethod: POST
                uri:
                  ##### TODO: Set function name
                  Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${tweeterGetStory.Arn}/invocations
                requestTemplates: *commonRequestTemplates
                responses: *commonAmazonResponses
              responses: *commonSwaggerResponses

          /followee/count: ##### TODO:DONE Set endpoint URL
            post:
              summary: "Gets the number of followees for a user"
              description: "Returns a number representing the number of followees a user has"
              consumes: *commonConsumes
              produces: *commonProduces
              x-amazon-apigateway-integration:
                type: aws
                httpMethod: POST
                uri:
                  ##### TODO: Set function name
                  Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${tweeterGetFolloweeCount.Arn}/invocations
                requestTemplates: *commonRequestTemplates
                responses: *commonAmazonResponses
              responses: *commonSwaggerResponses

          /follower/count: ##### TODO:DONE Set endpoint URL
            post:
              summary: "Gets the number of followers for a user"
              description: "Returns a number representing the number of followers a user has"
              consumes: *commonConsumes
              produces: *commonProduces
              x-amazon-apigateway-integration:
                type: aws
                httpMethod: POST
                uri:
                  ##### TODO: Set function name
                  Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${tweeterGetFollowerCount.Arn}/invocations
                requestTemplates: *commonRequestTemplates
                responses: *commonAmazonResponses
              responses: *commonSwaggerResponses

          /follower/status: ##### TODO:DONE Set endpoint URL
            post:
              summary: "Gets if a user is a follower of another user"
              description: "Returns a boolean value representing if the user follows the selectedUser"
              consumes: *commonConsumes
              produces: *commonProduces
              x-amazon-apigateway-integration:
                type: aws
                httpMethod: POST
                uri:
                  ##### TODO: Set function name
                  Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${tweeterGetFollowerStatus.Arn}/invocations
                requestTemplates: *commonRequestTemplates
                responses: *commonAmazonResponses
              responses: *commonSwaggerResponses

          /user/post: ##### TODO:DONE Set endpoint URL
            post:
              summary: "Post a status"
              description: "Posts a status for the specified user"
              consumes: *commonConsumes
              produces: *commonProduces
              x-amazon-apigateway-integration:
                type: aws
                httpMethod: POST
                uri:
                  ##### TODO: Set function name
                  Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${tweeterPostStatus.Arn}/invocations
                requestTemplates: *commonRequestTemplates
                responses: *commonAmazonResponses
              responses: *commonSwaggerResponses

          /user/get: ##### TODO:DONE Set endpoint URL
            post:
              summary: "Get a user"
              description: "Get a user by alias, if none is found, return null"
              consumes: *commonConsumes
              produces: *commonProduces
              x-amazon-apigateway-integration:
                type: aws
                httpMethod: POST
                uri:
                  ##### TODO: Set function name
                  Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${tweeterGetUser.Arn}/invocations
                requestTemplates: *commonRequestTemplates
                responses: *commonAmazonResponses
              responses: *commonSwaggerResponses

          #   #
          #   # TODO: ADD MORE ENDPOINT DEFINITIONS HERE
          #   #

  #
  # SQS Queues  (This will become relevant in Milestone 4. For M3, leave this section commented out.)
  #

  #   MyQueue:
  #     Type: AWS::SQS::Queue
  #     Properties:
  #       QueueName: MyQueue

  #
  # Lambda Layer (reused by all Lambda functions)
  #
  tweeterLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: tweeterLayer
      Description: dependencies layer for Tweeter server
      ContentUri: ./layer/
      CompatibleRuntimes:
        - nodejs22.x
      RetentionPolicy: DELETE

  #
  # Web API Lambda functions
  #

  ##### TODO:DONE Change "userGetFunction" to the actual function name.
  ##### It must match the function name in the "Endpoint definitons" section above.
  tweeterGetFollowees:
    Type: AWS::Serverless::Function
    Properties:
      ##### TODO:DONE Change "userGetFunction" to the actual function name.
      FunctionName: tweeterGetFollowees
      ##### TODO:DONE Modify Handler property to match your code. This identifies the exact function that the lambda should run.
      Handler: lambda/follow/GetFolloweesLambda.handler
      Policies: *commonPolicies
      Events:
        PostApi:
          Type: Api
          Properties:
            RestApiId:
              Ref: tweeterApi
            ##### TODO:DONE Modify the Path property to the actual endpoint URL.
            ##### It must match the URL in the "Endpoint definitions" section above.
            Path: /followee/list
            Method: POST

  tweeterGetFollowers: ##### TODO: Set function name
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: tweeterGetFollowers ##### TODO: Set function name
      Handler: lambda/follow/GetFollowersLambda.handler ##### TODO: Set Handler
      Policies: *commonPolicies
      Events:
        PostApi:
          Type: Api
          Properties:
            RestApiId:
              Ref: tweeterApi
            Path: /follower/list ##### TODO: Set Path
            Method: POST

  tweeterGetFeed: ##### TODO: Set function name
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: tweeterGetFeed ##### TODO: Set function name
      Handler: lambda/status/GetFeedLambda.handler ##### TODO: Set Handler
      Policies: *commonPolicies
      Events:
        PostApi:
          Type: Api
          Properties:
            RestApiId:
              Ref: tweeterApi
            Path: /feed/list ##### TODO: Set Path
            Method: POST

  tweeterGetStory: ##### TODO: Set function name
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: tweeterGetStory ##### TODO: Set function name
      Handler: lambda/status/GetStoryLambda.handler ##### TODO: Set Handler
      Policies: *commonPolicies
      Events:
        PostApi:
          Type: Api
          Properties:
            RestApiId:
              Ref: tweeterApi
            Path: /story/list ##### TODO: Set Path
            Method: POST

  tweeterGetFolloweeCount: ##### TODO: Set function name
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: tweeterGetFolloweeCount ##### TODO: Set function name
      Handler: lambda/follow/GetFolloweeCountLambda.handler ##### TODO: Set Handler
      Policies: *commonPolicies
      Events:
        PostApi:
          Type: Api
          Properties:
            RestApiId:
              Ref: tweeterApi
            Path: /followee/count ##### TODO: Set Path
            Method: POST

  tweeterGetFollowerCount: ##### TODO: Set function name
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: tweeterGetFollowerCount ##### TODO: Set function name
      Handler: lambda/follow/GetFollowerCountLambda.handler ##### TODO: Set Handler
      Policies: *commonPolicies
      Events:
        PostApi:
          Type: Api
          Properties:
            RestApiId:
              Ref: tweeterApi
            Path: /follower/count ##### TODO: Set Path
            Method: POST

  tweeterGetFollowerStatus: ##### TODO: Set function name
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: tweeterGetFollowerStatus ##### TODO: Set function name
      Handler: lambda/follow/GetFollowerStatusLambda.handler ##### TODO: Set Handler
      Policies: *commonPolicies
      Events:
        PostApi:
          Type: Api
          Properties:
            RestApiId:
              Ref: tweeterApi
            Path: /follower/status ##### TODO: Set Path
            Method: POST

  tweeterPostStatus: ##### TODO: Set function name
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: tweeterPostStatus ##### TODO: Set function name
      Handler: lambda/status/PostStatusLambda.handler ##### TODO: Set Handler
      Policies: *commonPolicies
      Events:
        PostApi:
          Type: Api
          Properties:
            RestApiId:
              Ref: tweeterApi
            Path: /user/post ##### TODO: Set Path
            Method: POST

  tweeterGetUser: ##### TODO: Set function name
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: tweeterGetUser ##### TODO: Set function name
      Handler: lambda/user/GetUserLambda.handler ##### TODO: Set Handler
      Policies: *commonPolicies
      Events:
        PostApi:
          Type: Api
          Properties:
            RestApiId:
              Ref: tweeterApi
            Path: /user/get ##### TODO: Set Path
            Method: POST

  # #
  # # TODO: ADD MORE WEB API LAMBDA DEFINITIONS HERE
  # #

  # #
  # # SQS Queue Lambda Functions  (This will become relevant in Milestone 4. For M3, leave this section commented out.)
  # #

  # #   MyQueueFunction:
  # #     Type: AWS::Serverless::Function
  # #     Properties:
  # #       FunctionName: MyQueueFunction
  # #       Handler: <PATH TO LAMBDA HANDLER>
  # #       Policies: *commonPolicies
  # #       Events:
  # #         SQSTrigger:
  # #           Type: SQS
  # #           Properties:
  # #             Queue: !GetAtt MyQueue.Arn
  # #             Enabled: true

  # #
  # # DynamoDB Tables
  # #

  # visitTable: ##### TODO: Change "visitTable" to match the table name. This doesn't
  #   #####       need to be the actual table name, just a unique identifier.
  #   Type: AWS::DynamoDB::Table
  #   Properties:
  #     TableName: visit ##### TODO: Set the actual table name. This is what your code will use to identify this table.
  #     AttributeDefinitions:
  #       ##### TODO: Add any attributes that will be used as partition or sort keys for the table or any indexes.
  #       - AttributeName: person_name
  #         AttributeType: S ##### TODO: Set the data type for this attribute. S for string, N for number, etc.
  #       - AttributeName: place_name
  #         AttributeType: S
  #     KeySchema:
  #       - AttributeName: person_name ##### TODO: Set the table partition key name
  #         KeyType: HASH
  #       - AttributeName: place_name ##### TODO: Set the table sort key name. Delete these
  #         KeyType: RANGE #####       two lines if the table has no sort key.
  #     BillingMode: PROVISIONED
  #     ProvisionedThroughput:
  #       ReadCapacityUnits: 1 ##### TODO: Set the table's Read and Write capacities. Leaving these at
  #       WriteCapacityUnits: 1 #####       one is fine for now, but you may need to change them later.
  #     ##### TODO: If you don't need an index for this table, delete the GlobalSecondaryIndexes property and all its subproperties.
  #     GlobalSecondaryIndexes:
  #       - IndexName: place_index ##### TODO: Set the actual index name. This is what your code will use to identify this index.
  #         KeySchema:
  #           - AttributeName: place_name ##### TODO: Set the index partition key name
  #             KeyType: HASH
  #           - AttributeName: person_name ##### TODO: Set the index sort key name. Delete these
  #             KeyType: RANGE #####       two lines if the index has no sort key.
  #         ProvisionedThroughput:
  #           ReadCapacityUnits: 1 ##### TODO: Same thing. Indexes have their own read/write
  #           WriteCapacityUnits: 1 #####       capacities that you may need to change.
  #         Projection:
  #           ProjectionType: ALL

  # followTable: ##### TODO: Change to match the table name
  #   Type: AWS::DynamoDB::Table
  #   Properties:
  #     TableName: follow ##### TODO: Set the actual table name
  #     AttributeDefinitions:
  #       ##### TODO: Add attributes that will be partition or sort keys, including their datatypes (for both table and index)
  #       - AttributeName: follower_alias
  #         AttributeType: S
  #       - AttributeName: followee_alias
  #         AttributeType: S
  #     KeySchema:
  #       - AttributeName: follower_alias ##### TODO: Set table partition key
  #         KeyType: HASH
  #       - AttributeName: followee_alias ##### TODO: Set table sort key
  #         KeyType: RANGE
  #     BillingMode: PROVISIONED
  #     ProvisionedThroughput:
  #       ReadCapacityUnits: 1
  #       WriteCapacityUnits: 1
  #     GlobalSecondaryIndexes:
  #       - IndexName: follow_index ##### TODO: Set the actual index name
  #         KeySchema:
  #           - AttributeName: followee_alias ##### TODO: Set index partition key
  #             KeyType: HASH
  #           - AttributeName: follower_alias ##### TODO: Set index sort key
  #             KeyType: RANGE
  #         ProvisionedThroughput:
  #           ReadCapacityUnits: 1
  #           WriteCapacityUnits: 1
  #         Projection:
  #           ProjectionType: ALL

  # #
  # # TODO: ADD MORE TABLE DEFINITIONS HERE
  # #
